### PR TITLE
Gemini

### PR DESCRIPTION
**Pull request by cephalization**

### CODE REVIEW

**Comment by AMaestroG** [comment]
I would like to be able to use groq, with llama 3 for its speed, - https://api.groq.com/openai/v1 -- Llama3-70b-8192 --

**Comment by blindmansion** [comment]
Good idea, we'll see about adding groq as well

**Comment by cephalization** [comment]
@AMaestroG same here, was actually going to add it to this PR as well and make it easier to add future providers

**Comment by cephalization** [comment]
Closing in favor of #28

**Pull request closed without merging**
